export const NotificationType = {
  MESSAGE: "MESSAGE",
  STATUS: "STATUS",
  TYPING: "TYPING",
  MESSAGE_DELETED: "MESSAGE_DELETED",
  MESSAGE_MARKED: "MESSAGE_MARKED",
  NEW_CHAT: "NEW_CHAT",
  TRANSACTION: "TRANSACTION",
};
