export const NotificationType = {
  MESSAGE: "MESSAGE",
  STATUS: "STATUS",
  TYPING: "TYPING",
  MESSAGE_DELETED: "MESSAGE_DELETED",
  MESSAGE_READ: "MESSAGE_READ",
  MESSAGE_DELIVERED: "MESSAGE_DELIVERED",
  NEW_CHAT: "NEW_CHAT",
  EXITED_CHAT: "EXITED_CHAT",
  TRANSACTION: "TRANSACTION",
};
